import 'package:flutter/material.dart';

class LocalizationService {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  static final ValueNotifier<String> currentLocale = ValueNotifier<String>('mr'); // Default Marathi per screenshots

  static final Map<String, String> supportedLanguages = {
    'en': 'English',
    'mr': 'मराठी',
    'hi': 'हिन्दी',
    'ta': 'தமிழ்',
    'te': 'తెలుగు',
    'bn': 'বাংলা',
    'kn': 'ಕನ್ನಡ',
  };

  static void setLocale(String langCode) {
    if (supportedLanguages.containsKey(langCode)) {
      currentLocale.value = langCode;
    }
  }

  static String t(String key) {
    final lang = currentLocale.value;
    if (_translations[lang]?.containsKey(key) ?? false) {
      return _translations[lang]![key]!;
    }
    // Fallback to English
    return _translations['en']?[key] ?? key;
  }

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'app_title': 'SahakarConnect',
      'tagline': 'Labour Cooperative Service Marketplace',
      'home': 'Home',
      'workers': 'Workers',
      'worker_portal': 'Worker Portal',
      'profile': 'Profile',
      'customer_mode': 'Customer Mode',
      'worker_mode': 'Worker Mode',
      'switch_to_worker': 'Switch to Worker Mode',
      'switch_to_customer': 'Switch to Customer Mode',
      'hero_title': 'Book Verified Labour Cooperative Service Providers',
      'hero_subtitle': 'Fair wages, direct bookings, zero exploitative middleman cuts',
      'categories': 'Service Categories',
      'top_workers': 'Top Cooperative Workers',
      'view_all': 'View All',
      'book_now': 'Book Now',
      'exp_years': 'years exp',
      'jobs_done': 'jobs done',
      'verified_badge': 'Govt Certified',
      'change_location': 'Change Location',
      'current_region': 'Bandra West, Mumbai',
      'all_providers': 'All Service Providers',
      'independent_labour': 'Independent Labour',
      'private_partner': 'Private Partner',
      'search_placeholder': 'Search workers or services...',
      'go_online': 'GO ONLINE',
      'go_offline': 'GO OFFLINE',
      'online_desc': 'Ready to receive nearby cooperative job offers',
      'offline_desc': 'Currently offline. Turn on to start earning',
      'earnings_today': "Today's Earnings",
      'completed_jobs': 'Completed Jobs',
      'rating': 'Rating',
      'new_offer_title': 'NEW SERVICE OFFER',
      'accept_job': 'ACCEPT JOB',
      'decline_job': 'DECLINE',
      'seconds_left': 'seconds left to accept',
      'payout_guarantee': 'Guaranteed Net Payout (88%)',
      'service_address': 'Service Address',
      'booking_timeline': 'Booking Status Timeline',
      'step_pending': 'Booking Created',
      'step_offered': 'Worker Dispatched',
      'step_accepted': 'Worker Accepted',
      'step_en_route': 'Worker En Route',
      'step_arrived': 'Worker Arrived',
      'step_in_progress': 'Job In Progress',
      'step_completed': 'Job Completed',
      'pay_now': 'Proceed to Payment',
      'split_worker': 'Worker Direct (88%)',
      'split_society': 'District Society (5%)',
      'split_platform': 'Platform Ops (4%)',
      'split_welfare': 'Worker Welfare Fund (3%)',
      'rate_worker': 'Rate Your Experience',
      'login_title': 'Welcome to SahakarConnect',
      'login_subtitle': 'Enter your mobile number to get started',
      'phone_label': 'Mobile Number',
      'send_otp': 'Send OTP Verification',
      'enter_otp': 'Enter 6-Digit OTP',
      'verify_continue': 'Verify & Continue',
      'resend_otp': 'Resend OTP',
      'logout': 'Log Out',
    },
    'mr': {
      'app_title': 'सहकार कनेक्ट',
      'tagline': 'कामगार सहकारी सेवा बाजारपेठ',
      'home': 'मुख्य',
      'workers': 'कामगार',
      'worker_portal': 'कामगार पोर्टल',
      'profile': 'प्रोफाईल',
      'customer_mode': 'ग्राहक मोड',
      'worker_mode': 'कामगार मोड',
      'switch_to_worker': 'कामगार मोडवर जा',
      'switch_to_customer': 'ग्राहक मोडवर जा',
      'hero_title': 'प्रमाणित कामगार सहकारी सेवा प्रदाते बुक करा',
      'hero_subtitle': 'वाजवी दर, थेट बुकिंग आणि ८८% थेट कामगारांना मोबदला',
      'categories': 'उपलब्ध सेवा श्रेणी',
      'top_workers': 'सर्वोत्कृष्ट सहकारी कामगार',
      'view_all': 'सर्व पहा',
      'book_now': 'आताच बुक करा',
      'exp_years': 'वर्षे अनुभव',
      'jobs_done': 'कामे पूर्ण',
      'verified_badge': 'शासकीय प्रमाणित',
      'change_location': 'स्थान बदला',
      'current_region': 'वांद्रे पश्चिम, मुंबई',
      'all_providers': 'सर्व सेवा प्रदाते',
      'independent_labour': 'स्वतंत्र कामगार',
      'private_partner': 'खाजगी भागीदार',
      'search_placeholder': 'कामगार किंवा सेवा शोधा...',
      'go_online': 'ऑनलाइन व्हा',
      'go_offline': 'ऑफलाइन व्हा',
      'online_desc': 'नवीन सेवा ऑर्डर्स स्वीकारण्यास सज्ज',
      'offline_desc': 'सध्या ऑफलाइन आहात. काम सुरू करण्यासाठी चालू करा',
      'earnings_today': 'आजची कमाई',
      'completed_jobs': 'पूर्ण झालेली कामे',
      'rating': 'रेटिंग',
      'new_offer_title': 'नवीन सेवा ऑफर आली आहे',
      'accept_job': 'काम स्वीकारा',
      'decline_job': 'नकार द्या',
      'seconds_left': 'सेकंद शिल्लक',
      'payout_guarantee': 'हमी दिलेली निव्वळ कमाई (८८%)',
      'service_address': 'सेवेचा पत्ता',
      'booking_timeline': 'बुकिंग प्रगती स्थिती',
      'step_pending': 'बुकिंग नोंदवली',
      'step_offered': 'कामगाराकडे पाठवली',
      'step_accepted': 'कामगाराने स्वीकारली',
      'step_en_route': 'कामगार मार्गावर आहे',
      'step_arrived': 'कामगार पोहोचला',
      'step_in_progress': 'काम चालू आहे',
      'step_completed': 'काम पूर्ण झाले',
      'pay_now': 'पैसे भरा',
      'split_worker': 'कामगार थेट (८८%)',
      'split_society': 'जिल्हा संस्था (५%)',
      'split_platform': 'प्लॅटफॉर्म व्यवस्थापन (४%)',
      'split_welfare': 'कामगार कल्याण निधी (३%)',
      'rate_worker': 'अनुभवाचे मूल्यांकन करा',
      'login_title': 'सहकार कनेक्ट मध्ये आपले स्वागत',
      'login_subtitle': 'सुरू करण्यासाठी आपला मोबाईल नंबर टाका',
      'phone_label': 'मोबाईल नंबर',
      'send_otp': 'ओटीपी पाठवा',
      'enter_otp': '६ अंकी ओटीपी टाका',
      'verify_continue': 'पडताळणी करा आणि पुढे जा',
      'resend_otp': 'पुन्हा ओटीपी पाठवा',
      'logout': 'बाहेर पडा',
    },
    'hi': {
      'app_title': 'सहकार कनेक्ट',
      'tagline': 'श्रमिक सहकारी सेवा मंच',
      'home': 'होम',
      'workers': 'कामगार',
      'worker_portal': 'कामगार पोर्टल',
      'profile': 'प्रोफाइल',
      'customer_mode': 'ग्राहक मोड',
      'worker_mode': 'कामगार मोड',
      'switch_to_worker': 'कामगार मोड में जाएं',
      'switch_to_customer': 'ग्राहक मोड में जाएं',
      'hero_title': 'सत्यापित श्रम सहकारी सेवा प्रदाता बुक करें',
      'hero_subtitle': 'उचित पारिश्रमिक, सीधी बुकिंग, बिचौलियों का कोई कमीशन नहीं',
      'categories': 'सेवा श्रेणियां',
      'top_workers': 'शीर्ष सहकारी कामगार',
      'view_all': 'सभी देखें',
      'book_now': 'अभी बुक करें',
      'exp_years': 'वर्ष अनुभव',
      'jobs_done': 'कार्य पूर्ण',
      'verified_badge': 'सरकारी प्रमाणित',
      'change_location': 'स्थान बदलें',
      'current_region': 'बांद्रा पश्चिम, मुंबई',
      'all_providers': 'सभी सेवा प्रदाता',
      'independent_labour': 'स्वतंत्र श्रमिक',
      'private_partner': 'निजी भागीदार',
      'search_placeholder': 'कामगार या सेवा खोजें...',
      'go_online': 'ऑनलाइन आएं',
      'go_offline': 'ऑफलाइन जाएं',
      'online_desc': 'नए काम के ऑर्डर स्वीकार करने के लिए तैयार',
      'offline_desc': 'वर्तमान में ऑफलाइन हैं',
      'earnings_today': 'आज की कमाई',
      'completed_jobs': 'पूर्ण कार्य',
      'rating': 'रेटिंग',
      'new_offer_title': 'नया सेवा प्रस्ताव',
      'accept_job': 'काम स्वीकारें',
      'decline_job': 'अस्वीकार करें',
      'seconds_left': 'सेकंड शेष',
      'payout_guarantee': 'गारंटीकृत शुद्ध भुगतान (88%)',
      'service_address': 'सेवा का पता',
      'booking_timeline': 'बुकिंग स्थिति',
      'step_pending': 'बुकिंग बनाई गई',
      'step_offered': 'कामगार को भेजा गया',
      'step_accepted': 'कामगार ने स्वीकारा',
      'step_en_route': 'कामगार रास्ते में है',
      'step_arrived': 'कामगार पहुंच गया',
      'step_in_progress': 'काम प्रगति पर है',
      'step_completed': 'काम पूरा हुआ',
      'pay_now': 'भुगतान करें',
      'split_worker': 'कामगार को प्रत्यक्ष (88%)',
      'split_society': 'जिला समिति (5%)',
      'split_platform': 'मंच रखरखाव (4%)',
      'split_welfare': 'श्रमिक कल्याण कोष (3%)',
      'rate_worker': 'रेटिंग दें',
      'login_title': 'सहकार कनेक्ट में स्वागत है',
      'login_subtitle': 'आगे बढ़ने के लिए मोबाइल नंबर दर्ज करें',
      'phone_label': 'मोबाइल नंबर',
      'send_otp': 'ओटीपी भेजें',
      'enter_otp': '6 अंकों का ओटीपी दर्ज करें',
      'verify_continue': 'सत्यापित करें और आगे बढ़ें',
      'resend_otp': 'ओटीपी पुनः भेजें',
      'logout': 'लॉग आउट',
    }
  };
}
