import 'package:flutter/material.dart';

class LocalizationService {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  static final ValueNotifier<String> currentLocale = ValueNotifier<String>('mr'); // Default Marathi

  static final Map<String, String> supportedLanguages = {
    'en': 'English',
    'mr': 'मराठी',
    'hi': 'हिन्दी',
    'ta': 'தமிழ்',
    'te': 'తెలుగు',
    'bn': 'বাংলা',
    'kn': 'ಕನ್ನಡ',
  };

  static void setLocale(String langCode) {
    if (supportedLanguages.containsKey(langCode)) {
      currentLocale.value = langCode;
    }
  }

  static String t(String key) {
    final lang = currentLocale.value;
    if (_translations[lang]?.containsKey(key) ?? false) {
      return _translations[lang]![key]!;
    }
    // Fallback to English
    return _translations['en']?[key] ?? key;
  }

  static final Map<String, Map<String, String>> _translations = {
    // -------------------------------------------------------------------------
    // 1. ENGLISH
    // -------------------------------------------------------------------------
    'en': {
      'app_title': 'SahakarConnect',
      'tagline': 'Labour Cooperative Service Marketplace',
      'home': 'Home',
      'workers': 'Workers',
      'worker_portal': 'Worker Portal',
      'my_bookings': 'My Bookings',
      'profile': 'Profile',
      'customer_mode': 'Customer Mode',
      'worker_mode': 'Worker Mode',
      'switch_to_worker': 'Switch to Worker Mode',
      'switch_to_customer': 'Switch to Customer Mode',
      'hero_title': 'Book Verified Labour Cooperative Service Providers',
      'hero_subtitle': 'Fair wages, direct bookings, zero exploitative middleman cuts',
      'categories': 'Service Categories',
      'top_workers': 'Top Cooperative Workers',
      'view_all': 'View All',
      'book_now': 'Book Now',
      'exp_years': 'years exp',
      'jobs_done': 'jobs done',
      'verified_badge': 'Govt Certified',
      'change_location': 'Change Location',
      'current_region': 'Bandra West, Mumbai',
      'all_providers': 'All Service Providers',
      'independent_labour': 'Independent Labour',
      'private_partner': 'Private Partner',
      'search_placeholder': 'Search workers or services...',
      'go_online': 'GO ONLINE',
      'go_offline': 'GO OFFLINE',
      'online_desc': 'Ready to receive nearby cooperative job offers',
      'offline_desc': 'Currently offline. Turn on to start earning',
      'earnings_today': "Today's Earnings",
      'completed_jobs': 'Completed Jobs',
      'rating': 'Rating',
      'new_offer_title': 'NEW SERVICE OFFER',
      'accept_job': 'ACCEPT JOB',
      'decline_job': 'DECLINE',
      'seconds_left': 'seconds left to accept',
      'payout_guarantee': 'Guaranteed Net Payout (88%)',
      'service_address': 'Service Address',
      'booking_timeline': 'Booking Status Timeline',
      'step_pending': 'Booking Created',
      'step_offered': 'Worker Dispatched',
      'step_accepted': 'Worker Accepted',
      'step_en_route': 'Worker En Route',
      'step_arrived': 'Worker Arrived',
      'step_in_progress': 'Job In Progress',
      'step_completed': 'Job Completed',
      'pay_now': 'Proceed to Payment',
      'split_worker': 'Worker Direct (88%)',
      'split_society': 'District Society (5%)',
      'split_platform': 'Platform Ops (4%)',
      'split_welfare': 'Worker Welfare Fund (3%)',
      'rate_worker': 'Rate Your Experience',
      'login_title': 'Welcome to SahakarConnect',
      'login_subtitle': 'Enter your mobile number to get started',
      'phone_label': 'Mobile Number',
      'send_otp': 'Send OTP Verification',
      'enter_otp': 'Enter 6-Digit OTP',
      'verify_continue': 'Verify & Continue',
      'resend_otp': 'Resend OTP',
      'logout': 'Log Out',
      'my_jobs': 'My Jobs',
      'map_view': 'Live Map',
      'worker_profile': 'Worker Profile',
      'worker_dashboard': 'Dashboard',
      'customer_details': 'Customer Contact Details',
      'call_customer': 'Call Customer',
      'active_jobs': 'Active Jobs',
      'past_jobs': 'Completed History',
      'no_active_jobs': 'No active jobs right now. Stay online to get orders!',
      'no_bookings': 'No bookings yet. Book a verified worker today!',
      'certification_title': 'Worker Verification & Certification',
      'certification_subtitle': 'Govt Cooperative Certified • Zero Fraud • Maximum Earnings',
      'aadhaar_verification': 'Aadhaar Verification',
      'aadhaar_desc': 'Verify your 12-digit Aadhaar to ensure identity and authenticity.',
      'face_card_title': 'Face Card & Fairness Verification',
      'face_card_desc': 'Live worker facial card to prevent impersonation and guarantee fair job distribution.',
      'trade_cert_title': 'Trade & Skill Certificates',
      'trade_cert_desc': 'Upload ITI, Skill Council or Trade licenses to unlock high-paying jobs.',
      'submit_verification': 'Submit for Cooperative Verification',
      'verification_status_pending': 'Verification In Review',
      'verification_status_verified': '100% Certified Member',
      'fairness_score_label': 'Cooperative Fairness Score',
      'nearby_demand': 'Nearby Customer Demand',
      'filter_radius': 'Radius Filter',
    },

    // -------------------------------------------------------------------------
    // 2. MARATHI (मराठी)
    // -------------------------------------------------------------------------
    'mr': {
      'app_title': 'सहकार कनेक्ट',
      'tagline': 'कामगार सहकारी सेवा बाजारपेठ',
      'home': 'मुख्य',
      'workers': 'कामगार',
      'worker_portal': 'कामगार पोर्टल',
      'my_bookings': 'माझी बुकिंग्स',
      'profile': 'प्रोफाईल',
      'customer_mode': 'ग्राहक मोड',
      'worker_mode': 'कामगार मोड',
      'switch_to_worker': 'कामगार मोडवर जा',
      'switch_to_customer': 'ग्राहक मोडवर जा',
      'hero_title': 'प्रमाणित कामगार सहकारी सेवा प्रदाते बुक करा',
      'hero_subtitle': 'वाजवी दर, थेट बुकिंग आणि ८८% थेट कामगारांना मोबदला',
      'categories': 'उपलब्ध सेवा श्रेणी',
      'top_workers': 'सर्वोत्कृष्ट सहकारी कामगार',
      'view_all': 'सर्व पहा',
      'book_now': 'आताच बुक करा',
      'exp_years': 'वर्षे अनुभव',
      'jobs_done': 'कामे पूर्ण',
      'verified_badge': 'शासकीय प्रमाणित',
      'change_location': 'स्थान बदला',
      'current_region': 'वांद्रे पश्चिम, मुंबई',
      'all_providers': 'सर्व सेवा प्रदाते',
      'independent_labour': 'स्वतंत्र कामगार',
      'private_partner': 'खाजगी भागीदार',
      'search_placeholder': 'कामगार किंवा सेवा शोधा...',
      'go_online': 'ऑनलाइन व्हा',
      'go_offline': 'ऑफलाइन व्हा',
      'online_desc': 'नवीन सेवा ऑर्डर्स स्वीकारण्यास सज्ज',
      'offline_desc': 'सध्या ऑफलाइन आहात. काम सुरू करण्यासाठी चालू करा',
      'earnings_today': 'आजची कमाई',
      'completed_jobs': 'पूर्ण झालेली कामे',
      'rating': 'रेटिंग',
      'new_offer_title': 'नवीन सेवा ऑफर आली आहे',
      'accept_job': 'काम स्वीकारा',
      'decline_job': 'नकार द्या',
      'seconds_left': 'सेकंद शिल्लक',
      'payout_guarantee': 'हमी दिलेली निव्वळ कमाई (८८%)',
      'service_address': 'सेवेचा पत्ता',
      'booking_timeline': 'बुकिंग प्रगती स्थिती',
      'step_pending': 'बुकिंग नोंदवली',
      'step_offered': 'कामगाराकडे पाठवली',
      'step_accepted': 'कामगाराने स्वीकारली',
      'step_en_route': 'कामगार मार्गावर आहे',
      'step_arrived': 'कामगार पोहोचला',
      'step_in_progress': 'काम चालू आहे',
      'step_completed': 'काम पूर्ण झाले',
      'pay_now': 'पैसे भरा',
      'split_worker': 'कामगार थेट (८८%)',
      'split_society': 'जिल्हा संस्था (५%)',
      'split_platform': 'प्लॅटफॉर्म व्यवस्थापन (४%)',
      'split_welfare': 'कामगार कल्याण निधी (३%)',
      'rate_worker': 'अनुभवाचे मूल्यांकन करा',
      'login_title': 'सहकार कनेक्ट मध्ये आपले स्वागत',
      'login_subtitle': 'सुरू करण्यासाठी आपला मोबाईल नंबर टाका',
      'phone_label': 'मोबाईल नंबर',
      'send_otp': 'ओटीपी पाठवा',
      'enter_otp': '६ अंकी ओटीपी टाका',
      'verify_continue': 'पडताळणी करा आणि पुढे जा',
      'resend_otp': 'पुन्हा ओटीपी पाठवा',
      'logout': 'बाहेर पडा',
      'my_jobs': 'माझी कामे',
      'map_view': 'नकाशा',
      'worker_profile': 'कामगार प्रोफाईल',
      'worker_dashboard': 'डॅशबोर्ड',
      'customer_details': 'ग्राहकाचा संपर्क तपशील',
      'call_customer': 'ग्राहकाला कॉल करा',
      'active_jobs': 'चालू कामे',
      'past_jobs': 'पूर्ण झालेला इतिहास',
      'no_active_jobs': 'सध्या कोणतेही काम चालू नाही. ऑर्डर्ससाठी ऑनलाइन राहा!',
      'no_bookings': 'अद्याप एकही बुकिंग नाही. आजच प्रमाणित कामगार बुक करा!',
      'certification_title': 'कामगार पडताळणी व प्रमाणपत्र',
      'certification_subtitle': 'शासकीय सहकारी प्रमाणित • शून्य फसवणूक • जास्तीत जास्त कमाई',
      'aadhaar_verification': 'आधार कार्ड पडताळणी',
      'aadhaar_desc': 'ओळख व सत्यतेसाठी आपला १२-अंकी आधार क्रमांक पडताळा.',
      'face_card_title': 'फेस कार्ड व पारदर्शकता पडताळणी',
      'face_card_desc': 'थेट चेहरा पडताळणीमुळे गैरवापर टळतो व कामाचे समान वाटप होते.',
      'trade_cert_title': 'व्यवसाय व कौशल्य प्रमाणपत्र',
      'trade_cert_desc': 'आयटीआय, कौशल्य परिषद प्रमाणपत्र जोडून उच्च उत्पन्न मिळवा.',
      'submit_verification': 'सहकारी पडताळणीसाठी सादर करा',
      'verification_status_pending': 'पडताळणी प्रक्रियेत आहे',
      'verification_status_verified': '१००% प्रमाणित सदस्य',
      'fairness_score_label': 'सहकारी निष्पक्षता स्कोअर',
      'nearby_demand': 'परिसरातील ग्राहकांची मागणी',
      'filter_radius': 'अंतर मर्यादा',
    },

    // -------------------------------------------------------------------------
    // 3. HINDI (हिन्दी)
    // -------------------------------------------------------------------------
    'hi': {
      'app_title': 'सहकार कनेक्ट',
      'tagline': 'श्रमिक सहकारी सेवा मंच',
      'home': 'होम',
      'workers': 'कामगार',
      'worker_portal': 'कामगार पोर्टल',
      'my_bookings': 'मेरी बुकिंग',
      'profile': 'प्रोफाइल',
      'customer_mode': 'ग्राहक मोड',
      'worker_mode': 'कामगार मोड',
      'switch_to_worker': 'कामगार मोड में जाएं',
      'switch_to_customer': 'ग्राहक मोड में जाएं',
      'hero_title': 'सत्यापित श्रम सहकारी सेवा प्रदाता बुक करें',
      'hero_subtitle': 'उचित पारिश्रमिक, सीधी बुकिंग, बिचौलियों का कोई कमीशन नहीं',
      'categories': 'सेवा श्रेणियां',
      'top_workers': 'शीर्ष सहकारी कामगार',
      'view_all': 'सभी देखें',
      'book_now': 'अभी बुक करें',
      'exp_years': 'वर्ष अनुभव',
      'jobs_done': 'कार्य पूर्ण',
      'verified_badge': 'सरकारी प्रमाणित',
      'change_location': 'स्थान बदलें',
      'current_region': 'बांद्रा पश्चिम, मुंबई',
      'all_providers': 'सभी सेवा प्रदाता',
      'independent_labour': 'स्वतंत्र श्रमिक',
      'private_partner': 'निजी भागीदार',
      'search_placeholder': 'कामगार या सेवा खोजें...',
      'go_online': 'ऑनलाइन आएं',
      'go_offline': 'ऑफलाइन जाएं',
      'online_desc': 'नए काम के ऑर्डर स्वीकार करने के लिए तैयार',
      'offline_desc': 'वर्तमान में ऑफलाइन हैं',
      'earnings_today': 'आज की कमाई',
      'completed_jobs': 'पूर्ण कार्य',
      'rating': 'रेटिंग',
      'new_offer_title': 'नया सेवा प्रस्ताव',
      'accept_job': 'काम स्वीकारें',
      'decline_job': 'अस्वीकार करें',
      'seconds_left': 'सेकंड शेष',
      'payout_guarantee': 'गारंटीकृत शुद्ध भुगतान (88%)',
      'service_address': 'सेवा का पता',
      'booking_timeline': 'बुकिंग स्थिति',
      'step_pending': 'बुकिंग बनाई गई',
      'step_offered': 'कामगार को भेजा गया',
      'step_accepted': 'कामगार ने स्वीकारा',
      'step_en_route': 'कामगार रास्ते में है',
      'step_arrived': 'कामगार पहुंच गया',
      'step_in_progress': 'काम प्रगति पर है',
      'step_completed': 'काम पूरा हुआ',
      'pay_now': 'भुगतान करें',
      'split_worker': 'कामगार को प्रत्यक्ष (88%)',
      'split_society': 'जिला समिति (5%)',
      'split_platform': 'मंच रखरखाव (4%)',
      'split_welfare': 'श्रमिक कल्याण कोष (3%)',
      'rate_worker': 'रेटिंग दें',
      'login_title': 'सहकार कनेक्ट में स्वागत है',
      'login_subtitle': 'आगे बढ़ने के लिए मोबाइल नंबर दर्ज करें',
      'phone_label': 'मोबाइल नंबर',
      'send_otp': 'ओटीपी भेजें',
      'enter_otp': '6 अंकों का ओटीपी दर्ज करें',
      'verify_continue': 'सत्यापित करें और आगे बढ़ें',
      'resend_otp': 'ओटीपी पुनः भेजें',
      'logout': 'लॉग आउट',
      'my_jobs': 'मेरे काम',
      'map_view': 'नक्शा',
      'worker_profile': 'कामगार प्रोफाइल',
      'worker_dashboard': 'डैशबोर्ड',
      'customer_details': 'ग्राहक संपर्क विवरण',
      'call_customer': 'ग्राहक को कॉल करें',
      'active_jobs': 'सक्रिय कार्य',
      'past_jobs': 'पूर्ण इतिहास',
      'no_active_jobs': 'वर्तमान में कोई सक्रिय कार्य नहीं है। ऑनलाइन रहें!',
      'no_bookings': 'अभी तक कोई बुकिंग नहीं। आज ही सत्यापित कामगार बुक करें!',
      'certification_title': 'कामगार सत्यापन एवं प्रमाणन',
      'certification_subtitle': 'सरकारी सहकारी प्रमाणित • कोई धोखाधड़ी नहीं • अधिकतम कमाई',
      'aadhaar_verification': 'आधार सत्यापन',
      'aadhaar_desc': 'पहचान सत्यापन के लिए अपना 12-अंकीय आधार नंबर दर्ज करें।',
      'face_card_title': 'फेस कार्ड एवं निष्पक्षता जांच',
      'face_card_desc': 'फर्जी प्रोफाइल रोकने और निष्पक्ष काम के लिए लाइव चेहरा सत्यापन।',
      'trade_cert_title': 'कौशल एवं ट्रेड प्रमाण पत्र',
      'trade_cert_desc': 'आईटीआई या कौशल प्रमाण पत्र अपलोड कर अधिक आय वाले काम पाएं।',
      'submit_verification': 'सत्यापन के लिए भेजें',
      'verification_status_pending': 'सत्यापन समीक्षा में है',
      'verification_status_verified': '100% प्रमाणित सदस्य',
      'fairness_score_label': 'सहकारी निष्पक्षता स्कोर',
      'nearby_demand': 'आसपास की ग्राहक मांग',
      'filter_radius': 'दायरा फिल्टर',
    },

    // -------------------------------------------------------------------------
    // 4. TAMIL (தமிழ்)
    // -------------------------------------------------------------------------
    'ta': {
      'app_title': 'சஹாகார் கனெக்ட்',
      'tagline': 'தொழிலாளர் கூட்டுறவு சேவை தளம்',
      'home': 'முகப்பு',
      'workers': 'பணியாளர்கள்',
      'worker_portal': 'பணியாளர் தளம்',
      'my_bookings': 'எனது முன்பதிவுகள்',
      'profile': 'சுயவிவரம்',
      'customer_mode': 'வாடிக்கையாளர் பயன்முறை',
      'worker_mode': 'பணியாளர் பயன்முறை',
      'switch_to_worker': 'பணியாளர் பயன்முறைக்கு மாறுக',
      'switch_to_customer': 'வாடிக்கையாளர் பயன்முறைக்கு மாறுக',
      'hero_title': 'சரிபார்க்கப்பட்ட கூட்டுறவு தொழிலாளர்களை முன்பதிவு செய்யுங்கள்',
      'hero_subtitle': 'நியாயமான ஊதியம், நேரடி முன்பதிவு, இடைத்தரகர் கமிஷன் இல்லை',
      'categories': 'சேவை பிரிவுகள்',
      'top_workers': 'சிறந்த கூட்டுறவு தொழிலாளர்கள்',
      'view_all': 'அனைத்தையும் காண்க',
      'book_now': 'இப்போதே பதிவு செய்க',
      'exp_years': 'ஆண்டுகள் அனுபவம்',
      'jobs_done': 'முடித்த பணிகள்',
      'verified_badge': 'அரசு சான்றளிக்கப்பட்டது',
      'change_location': 'இருப்பிடத்தை மாற்றுக',
      'current_region': 'பாந்த்ரா மேற்கு, மும்பை',
      'all_providers': 'அனைத்து சேவை வழங்குநர்கள்',
      'independent_labour': 'சுயாதீன தொழிலாளி',
      'private_partner': 'தனியார் கூட்டாளர்',
      'search_placeholder': 'பணியாளர்கள் அல்லது சேவைகளைத் தேடுங்கள்...',
      'go_online': 'ஆன்லைனில் செல்லவும்',
      'go_offline': 'ஆஃப்லைனில் செல்லவும்',
      'online_desc': 'புதிய வேலை வாய்ப்புகளைப் பெற தயார்',
      'offline_desc': 'தற்போது ஆஃப்லைனில் உள்ளீர்கள்',
      'earnings_today': 'இன்றைய வருமானம்',
      'completed_jobs': 'முடித்த பணிகள்',
      'rating': 'மதிப்பீடு',
      'new_offer_title': 'புதிய சேவை வாய்ப்பு',
      'accept_job': 'ஏற்கவும்',
      'decline_job': 'நிராகரி',
      'seconds_left': 'வினாடிகள் உள்ளன',
      'payout_guarantee': 'உறுதிசெய்யப்பட்ட ஊதியம் (88%)',
      'service_address': 'சேவை முகவரி',
      'booking_timeline': 'முன்பதிவு நிலை',
      'step_pending': 'முன்பதிவு செய்யப்பட்டது',
      'step_offered': 'பணியாளருக்கு அனுப்பப்பட்டது',
      'step_accepted': 'பணியாளர் ஏற்றார்',
      'step_en_route': 'பணியாளர் வழியில் உள்ளார்',
      'step_arrived': 'பணியாளர் வந்துவிட்டார்',
      'step_in_progress': 'வேலை நடக்கிறது',
      'step_completed': 'வேலை முடிந்தது',
      'pay_now': 'பணம் செலுத்துங்கள்',
      'split_worker': 'பணியாளருக்கு நேரடியாக (88%)',
      'split_society': 'மாவட்ட சங்கம் (5%)',
      'split_platform': 'தள பராமரிப்பு (4%)',
      'split_welfare': 'தொழிலாளர் நல நிதி (3%)',
      'rate_worker': 'மதிப்பிடவும்',
      'login_title': 'சஹாகார் கனெக்டிற்கு வரவேற்கிறோம்',
      'login_subtitle': 'தொடங்க உங்கள் மொபைல் எண்ணை உள்ளிடவும்',
      'phone_label': 'மொபைல் எண்',
      'send_otp': 'OTP அனுப்பவும்',
      'enter_otp': '6 இலக்க OTP ஐ உள்ளிடவும்',
      'verify_continue': 'சரிபார்த்து தொடரவும்',
      'resend_otp': 'மீண்டும் OTP அனுப்பவும்',
      'logout': 'வெளியேறு',
      'my_jobs': 'எனது வேலைகள்',
      'map_view': 'நேரலை வரைபடம்',
      'worker_profile': 'பணியாளர் விவரம்',
      'worker_dashboard': 'டாஷ்போர்டு',
      'customer_details': 'வாடிக்கையாளர் தொடர்பு விவரங்கள்',
      'call_customer': 'வாடிக்கையாளரை அழைக்கவும்',
      'active_jobs': 'நடப்பு வேலைகள்',
      'past_jobs': 'கடந்த வேலைகள்',
      'no_active_jobs': 'தற்போது நடப்பு வேலைகள் ஏதுமில்லை.',
      'no_bookings': 'இன்னும் முன்பதிவு ஏதுமில்லை.',
      'certification_title': 'பணியாளர் சரிபார்ப்பு & சான்றிதழ்',
      'certification_subtitle': 'அரசு சான்றளிக்கப்பட்டது • நியாயமான வாய்ப்பு',
      'aadhaar_verification': 'ஆதார் சரிபார்ப்பு',
      'aadhaar_desc': 'உங்கள் 12 இலக்க ஆதார் எண்ணை உள்ளிடவும்.',
      'face_card_title': 'முக அட்டை & நம்பகத்தன்மை சரிபார்ப்பு',
      'face_card_desc': 'ஆள்மாறாட்டத்தைத் தடுக்க நேரடி முக சரிபார்ப்பு.',
      'trade_cert_title': 'தொழில் திறன் சான்றிதழ்',
      'trade_cert_desc': 'ITI அல்லது திறன் சான்றிதழ்களை பதிவேற்றவும்.',
      'submit_verification': 'சரிபார்ப்புக்கு சமர்ப்பிக்கவும்',
      'verification_status_pending': 'சரிபார்ப்பு நிலுவையில் உள்ளது',
      'verification_status_verified': '100% சான்றளிக்கப்பட்ட உறுப்பினர்',
      'fairness_score_label': 'கூட்டுறவு நியாய மதிப்பெண்',
      'nearby_demand': 'அருகிலுள்ள வாடிக்கையாளர் தேவை',
      'filter_radius': 'சுற்றளவு வடிகட்டி',
    },

    // -------------------------------------------------------------------------
    // 5. TELUGU (తెలుగు)
    // -------------------------------------------------------------------------
    'te': {
      'app_title': 'సహకార్ కనెక్ట్',
      'tagline': 'కార్మిక సహకార సేవా వేదిక',
      'home': 'హోమ్',
      'workers': 'కార్మికులు',
      'worker_portal': 'కార్మిక పోర్టల్',
      'my_bookings': 'నా బుకింగ్‌లు',
      'profile': 'ప్రొఫైల్',
      'customer_mode': 'కస్టమర్ మోడ్',
      'worker_mode': 'కార్మిక మోడ్',
      'switch_to_worker': 'కార్మిక మోడ్‌కు మారండి',
      'switch_to_customer': 'కస్టమర్ మోడ్‌కు మారండి',
      'hero_title': 'ధృవీకరించబడిన సహకార కార్మికులను బుక్ చేసుకోండి',
      'hero_subtitle': 'న్యాయమైన వేతనం, ప్రత్యక్ష బుకింగ్, మధ్యవర్తుల కమిషన్ లేదు',
      'categories': 'సేవా వర్గాలు',
      'top_workers': 'ఉత్తమ సహకార కార్మికులు',
      'view_all': 'అన్నీ చూడండి',
      'book_now': 'ఇప్పుడే బుక్ చేయండి',
      'exp_years': 'సంవత్సరాల అనుభవం',
      'jobs_done': 'పూర్తయిన పనులు',
      'verified_badge': 'ప్రభుత్వ ధృవీకృతం',
      'change_location': 'ప్రాంతం మార్చండి',
      'current_region': 'బాంద్రా వెస్ట్, ముంబై',
      'all_providers': 'అన్ని సేవా ప్రదాతలు',
      'independent_labour': 'స్వతంత్ర కార్మికుడు',
      'private_partner': 'ప్రైవేట్ భాగస్వామి',
      'search_placeholder': 'కార్మికులు లేదా సేవలను శోధించండి...',
      'go_online': 'ఆన్‌లైన్‌కు వెళ్లండి',
      'go_offline': 'ఆఫ్‌లైన్‌కు వెళ్లండి',
      'online_desc': 'కొత్త పని ఆర్డర్‌లను స్వీకరించడానికి సిద్ధంగా ఉంది',
      'offline_desc': 'ప్రస్తుతం ఆఫ్‌లైన్‌లో ఉన్నారు',
      'earnings_today': 'నేటి ఆదాయం',
      'completed_jobs': 'పూర్తయిన పనులు',
      'rating': 'రేటింగ్',
      'new_offer_title': 'కొత్త సేవా ఆఫర్',
      'accept_job': 'అంగీకరించు',
      'decline_job': 'తిరస్కరించు',
      'seconds_left': 'సెకన్లు మిగిలి ఉన్నాయి',
      'payout_guarantee': 'హామీ ఇవ్వబడిన వేతనం (88%)',
      'service_address': 'సేవా చిరునామా',
      'booking_timeline': 'బుకింగ్ స్థితి',
      'step_pending': 'బుకింగ్ చేయబడింది',
      'step_offered': 'కార్మికుడికి పంపబడింది',
      'step_accepted': 'కార్మికుడు అంగీకరించారు',
      'step_en_route': 'కార్మికుడు మార్గంలో ఉన్నారు',
      'step_arrived': 'కార్మికుడు వచ్చారు',
      'step_in_progress': 'పని జరుగుతోంది',
      'step_completed': 'పని పూర్తయింది',
      'pay_now': 'చెల్లించండి',
      'split_worker': 'కార్మికుడికి నేరుగా (88%)',
      'split_society': 'జిల్లా సంఘం (5%)',
      'split_platform': 'ప్లాట్‌ఫారమ్ నిర్వహణ (4%)',
      'split_welfare': 'కార్మిక సంక్షేమ నిధి (3%)',
      'rate_worker': 'రేటింగ్ ఇవ్వండి',
      'login_title': 'సహకార్ కనెక్ట్‌కు స్వాగతం',
      'login_subtitle': 'ప్రారంభించడానికి మీ మొబైల్ నంబర్ నమోదు చేయండి',
      'phone_label': 'మొబైల్ నంబర్',
      'send_otp': 'OTP పంపండి',
      'enter_otp': '6 అంకెల OTP నమోదు చేయండి',
      'verify_continue': 'ధృవీకరించి కొనసాగండి',
      'resend_otp': 'మళ్లీ OTP పంపండి',
      'logout': 'లాగ్ అవుట్',
      'my_jobs': 'నా పనులు',
      'map_view': 'లైవ్ మ్యాప్',
      'worker_profile': 'కార్మిక ప్రొఫైల్',
      'worker_dashboard': 'డాష్‌బోర్డ్',
      'customer_details': 'కస్టమర్ సంప్రదింపు వివరాలు',
      'call_customer': 'కస్టమర్‌కు కాల్ చేయండి',
      'active_jobs': 'ప్రస్తుత పనులు',
      'past_jobs': 'పూర్తయిన పనుల చరిత్ర',
      'no_active_jobs': 'ప్రస్తుతం పనులేవీ లేవు.',
      'no_bookings': 'ఇంకా బుకింగ్‌లు లేవు.',
      'certification_title': 'కార్మిక ధృవీకరణ & సర్టిఫికేషన్',
      'certification_subtitle': 'ప్రభుత్వ సహకార ధృవీకృతం • అధిక ఆదాయం',
      'aadhaar_verification': 'ఆధార్ ధృవీకరణ',
      'aadhaar_desc': 'మీ 12 అంకెల ఆధార్ నంబర్‌ను నమోదు చేయండి.',
      'face_card_title': 'ఫేస్ కార్డ్ & న్యాయబద్ధత ధృవీకరణ',
      'face_card_desc': 'మోసాలను నివారించడానికి ప్రత్యక్ష ముఖ గుర్తింపు.',
      'trade_cert_title': 'నైపుణ్య ధృవీకరణ పత్రాలు',
      'trade_cert_desc': 'ITI లేదా నైపుణ్య సర్టిఫికెట్లను అప్‌లోడ్ చేయండి.',
      'submit_verification': 'సహకార ధృవీకరణకు సమర్పించండి',
      'verification_status_pending': 'ధృవీకరణ సమీక్షలో ఉంది',
      'verification_status_verified': '100% ధృవీకరించబడిన సభ్యుడు',
      'fairness_score_label': 'సహకార న్యాయబద్ధత స్కోరు',
      'nearby_demand': 'సమీప కస్టమర్ డిమాండ్',
      'filter_radius': 'పరిధి ఫిల్టర్',
    },

    // -------------------------------------------------------------------------
    // 6. BENGALI (বাংলা)
    // -------------------------------------------------------------------------
    'bn': {
      'app_title': 'সহকার কানেক্ট',
      'tagline': 'শ্রম সমবায় পরিষেবা বাজার',
      'home': 'হোম',
      'workers': 'শ্রমিক',
      'worker_portal': 'শ্রমিক পোর্টাল',
      'my_bookings': 'আমার বুকিং',
      'profile': 'প্রোফাইল',
      'customer_mode': 'গ্রাহক মোড',
      'worker_mode': 'শ্রমিক মোড',
      'switch_to_worker': 'শ্রমিক মোডে যান',
      'switch_to_customer': 'গ্রাহক মোডে যান',
      'hero_title': 'যাচাইকৃত শ্রম সমবায় পরিষেবা বুক করুন',
      'hero_subtitle': 'ন্যায্য মজুরি, সরাসরি বুকিং, কোনো মধ্যস্থতাকারীর কমিশন নেই',
      'categories': 'পরিষেবা বিভাগ',
      'top_workers': 'শীর্ষ সমবায় কর্মী',
      'view_all': 'সব দেখুন',
      'book_now': 'এখনই বুক করুন',
      'exp_years': 'বছরের অভিজ্ঞতা',
      'jobs_done': 'কাজ সম্পন্ন',
      'verified_badge': 'সরকারি প্রত্যয়িত',
      'change_location': 'স্থান পরিবর্তন করুন',
      'current_region': 'বান্দ্রা পশ্চিম, মুম্বাই',
      'all_providers': 'সকল পরিষেবা প্রদানকারী',
      'independent_labour': 'স্বাধীন শ্রমিক',
      'private_partner': 'ব্যক্তিগত অংশীদার',
      'search_placeholder': 'শ্রমিক বা পরিষেবা অনুসন্ধান করুন...',
      'go_online': 'অনলাইনে যান',
      'go_offline': 'অফলাইনে যান',
      'online_desc': 'নতুন কাজের প্রস্তাব গ্রহণের জন্য প্রস্তুত',
      'offline_desc': 'বর্তমানে অফলাইনে আছেন',
      'earnings_today': 'আজকের আয়',
      'completed_jobs': 'সম্পন্ন কাজ',
      'rating': 'রেটিং',
      'new_offer_title': 'নতুন কাজের প্রস্তাব',
      'accept_job': 'গ্রহণ করুন',
      'decline_job': 'প্রত্যাখ্যান করুন',
      'seconds_left': 'সেকেন্ড বাকি',
      'payout_guarantee': 'নিশ্চিত মজুরি (৮৮%)',
      'service_address': 'পরিষেবার ঠিকানা',
      'booking_timeline': 'বুকিং স্থিতি',
      'step_pending': 'বুকিং সম্পন্ন হয়েছে',
      'step_offered': 'কর্মীর কাছে পাঠানো হয়েছে',
      'step_accepted': 'কর্মী গ্রহণ করেছেন',
      'step_en_route': 'কর্মী পথে আছেন',
      'step_arrived': 'কর্মী পৌঁছে গেছেন',
      'step_in_progress': 'কাজ চলছে',
      'step_completed': 'কাজ সম্পন্ন হয়েছে',
      'pay_now': 'টাকা পরিশোধ করুন',
      'split_worker': 'সরাসরি কর্মীকে (৮৮%)',
      'split_society': 'জেলা সমিতি (৫%)',
      'split_platform': 'প্ল্যাটফর্ম ব্যবস্থাপনা (৪%)',
      'split_welfare': 'শ্রমিক কল্যাণ তহবিল (৩%)',
      'rate_worker': 'রেটিং দিন',
      'login_title': 'সহকার কানেক্টে স্বাগতম',
      'login_subtitle': 'শুরু করতে আপনার মোবাইল নম্বর লিখুন',
      'phone_label': 'মোবাইল নম্বর',
      'send_otp': 'OTP পাঠান',
      'enter_otp': '৬ সংখ্যার OTP লিখুন',
      'verify_continue': 'যাচাই করে এগিয়ে যান',
      'resend_otp': 'পুনরায় OTP পাঠান',
      'logout': 'লগ আউট',
      'my_jobs': 'আমার কাজ',
      'map_view': 'লাইভ ম্যাপ',
      'worker_profile': 'শ্রমিক প্রোফাইল',
      'worker_dashboard': 'ড্যাশবোর্ড',
      'customer_details': 'গ্রাহকের যোগাযোগের বিবরণ',
      'call_customer': 'গ্রাহককে কল করুন',
      'active_jobs': 'চলমান কাজ',
      'past_jobs': 'সম্পন্ন কাজের ইতিহাস',
      'no_active_jobs': 'বর্তমানে কোনো সক্রিয় কাজ নেই।',
      'no_bookings': 'এখনো কোনো বুকিং নেই।',
      'certification_title': 'কর্মী যাচাই ও সার্টিফিকেশন',
      'certification_subtitle': 'সরকারি সমবায় প্রত্যয়িত • সর্বোচ্চ আয়',
      'aadhaar_verification': 'আধার যাচাইকরণ',
      'aadhaar_desc': 'আপনার ১২ সংখ্যার আধার নম্বর লিখুন।',
      'face_card_title': 'ফেস কার্ড ও সততা যাচাই',
      'face_card_desc': 'জালিয়াতি রোধে লাইভ ফেস ভেরিফিকেশন।',
      'trade_cert_title': 'দক্ষতা ও ট্রেড সার্টিফিকেট',
      'trade_cert_desc': 'উচ্চ আয়ের কাজের জন্য সার্টিফিকেট আপলোড করুন।',
      'submit_verification': 'যাচাইয়ের জন্য জমা দিন',
      'verification_status_pending': 'যাচাইকরণ প্রক্রিয়াধীন',
      'verification_status_verified': '১০০% প্রত্যয়িত সদস্য',
      'fairness_score_label': 'সমবায় ন্যায্যতা স্কোর',
      'nearby_demand': 'নিকটবর্তী গ্রাহকের চাহিদা',
      'filter_radius': 'দূরত্ব ফিল্টার',
    },

    // -------------------------------------------------------------------------
    // 7. KANNADA (ಕನ್ನಡ)
    // -------------------------------------------------------------------------
    'kn': {
      'app_title': 'ಸಹಕಾರ್ ಕನೆಕ್ಟ್',
      'tagline': 'ಕಾರ್ಮಿಕ ಸಹಕಾರಿ ಸೇವಾ ಮಾರುಕಟ್ಟೆ',
      'home': 'ಮುಖಪುಟ',
      'workers': 'ಕಾರ್ಮಿಕರು',
      'worker_portal': 'ಕಾರ್ಮಿಕ ಪೋರ್ಟಲ್',
      'my_bookings': 'ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'customer_mode': 'ಗ್ರಾಹಕ ಮೋಡ್',
      'worker_mode': 'ಕಾರ್ಮಿಕ ಮೋಡ್',
      'switch_to_worker': 'ಕಾರ್ಮಿಕ ಮೋಡ್‌ಗೆ ಬದಲಾಯಿಸಿ',
      'switch_to_customer': 'ಗ್ರಾಹಕ ಮೋಡ್‌ಗೆ ಬದಲಾಯಿಸಿ',
      'hero_title': 'ದೃಢೀಕೃತ ಸಹಕಾರಿ ಕಾರ್ಮಿಕರನ್ನು ಬುಕ್ ಮಾಡಿ',
      'hero_subtitle': 'ನ್ಯಾಯಯುತ ವೇತನ, ನೇರ ಬುಕಿಂಗ್, ಮಧ್ಯವರ್ತಿಗಳ ಕಮಿಷನ್ ಇಲ್ಲ',
      'categories': 'ಸೇವಾ ವಿಭಾಗಗಳು',
      'top_workers': 'ಉನ್ನತ ಸಹಕಾರಿ ಕಾರ್ಮಿಕರು',
      'view_all': 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
      'book_now': 'ಈಗಲೇ ಬುಕ್ ಮಾಡಿ',
      'exp_years': 'ವರ್ಷಗಳ ಅನುಭವ',
      'jobs_done': 'ಪೂರ್ಣಗೊಳಿಸಿದ ಕೆಲಸಗಳು',
      'verified_badge': 'ಸರ್ಕಾರಿ ಪ್ರಮಾಣೀಕೃತ',
      'change_location': 'ಸ್ಥಳ ಬದಲಾಯಿಸಿ',
      'current_region': 'ಬಾಂದ್ರಾ ಪಶ್ಚಿಮ, ಮುಂಬೈ',
      'all_providers': 'ಎಲ್ಲಾ ಸೇವಾ ಪೂರೈಕೆದಾರರು',
      'independent_labour': 'ಸ್ವತಂತ್ರ ಕಾರ್ಮಿಕ',
      'private_partner': 'ಖಾಸಗಿ ಪಾಲುದಾರ',
      'search_placeholder': 'ಕಾರ್ಮಿಕರು ಅಥವಾ ಸೇವೆಗಳನ್ನು ಹುಡುಕಿ...',
      'go_online': 'ಆನ್‌ಲೈನ್‌ಗೆ ಹೋಗಿ',
      'go_offline': 'ಆಫ್‌ಲೈನ್‌ಗೆ ಹೋಗಿ',
      'online_desc': 'ಹೊಸ ಕೆಲಸದ ಆದೇಶಗಳನ್ನು ಸ್ವೀಕರಿಸಲು ಸಿದ್ಧವಾಗಿದೆ',
      'offline_desc': 'ಪ್ರಸ್ತುತ ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿದ್ದೀರಿ',
      'earnings_today': 'ಇಂದಿನ ಗಳಿಕೆ',
      'completed_jobs': 'ಪೂರ್ಣಗೊಂಡ ಕೆಲಸಗಳು',
      'rating': 'ರೇಟಿಂಗ್',
      'new_offer_title': 'ಹೊಸ ಸೇವಾ ಪ್ರಸ್ತಾಪ',
      'accept_job': 'ಸ್ವೀಕರಿಸಿ',
      'decline_job': 'ತಿರಸ್ಕರಿಸಿ',
      'seconds_left': 'ಸೆಕೆಂಡುಗಳು ಬಾಕಿ ಇವೆ',
      'payout_guarantee': 'ಖಾತರಿಪಡಿಸಿದ ವೇತನ (88%)',
      'service_address': 'ಸೇವಾ ವಿಳಾಸ',
      'booking_timeline': 'ಬುಕಿಂಗ್ ಸ್ಥಿತಿ',
      'step_pending': 'ಬುಕಿಂಗ್ ಮಾಡಲಾಗಿದೆ',
      'step_offered': 'ಕಾರ್ಮಿಕರಿಗೆ ಕಳುಹಿಸಲಾಗಿದೆ',
      'step_accepted': 'ಕಾರ್ಮಿಕರು ಒಪ್ಪಿಕೊಂಡಿದ್ದಾರೆ',
      'step_en_route': 'ಕಾರ್ಮಿಕರು ದಾರಿಯಲ್ಲಿದ್ದಾರೆ',
      'step_arrived': 'ಕಾರ್ಮಿಕರು ತಲುಪಿದ್ದಾರೆ',
      'step_in_progress': 'ಕೆಲಸ ಪ್ರಗತಿಯಲ್ಲಿದೆ',
      'step_completed': 'ಕೆಲಸ ಪೂರ್ಣಗೊಂಡಿದೆ',
      'pay_now': 'ಹಣ ಪಾವತಿಸಿ',
      'split_worker': 'ಕಾರ್ಮಿಕರಿಗೆ ನೇರವಾಗಿ (88%)',
      'split_society': 'ಜಿಲ್ಲಾ ಸಂಘ (5%)',
      'split_platform': 'ವೇದಿಕೆ ನಿರ್ವಹಣೆ (4%)',
      'split_welfare': 'ಕಾರ್ಮಿಕ ಕಲ್ಯಾಣ ನಿಧಿ (3%)',
      'rate_worker': 'ರೇಟಿಂಗ್ ನೀಡಿ',
      'login_title': 'ಸಹಕಾರ್ ಕನೆಕ್ಟ್‌ಗೆ ಸುಸ್ವಾಗತ',
      'login_subtitle': 'ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
      'phone_label': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'send_otp': 'OTP ಕಳುಹಿಸಿ',
      'enter_otp': '6 ಅಂಕಿಯ OTP ನಮೂದಿಸಿ',
      'verify_continue': 'ದೃಢೀಕರಿಸಿ ಮತ್ತು ಮುಂದುವರಿಯಿರಿ',
      'resend_otp': 'ಮತ್ತೊಮ್ಮೆ OTP ಕಳುಹಿಸಿ',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'my_jobs': 'ನನ್ನ ಕೆಲಸಗಳು',
      'map_view': 'ಲೈವ್ ನಕ್ಷೆ',
      'worker_profile': 'ಕಾರ್ಮಿಕ ಪ್ರೊಫೈಲ್',
      'worker_dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'customer_details': 'ಗ್ರಾಹಕರ ಸಂಪರ್ಕ ವಿವರಗಳು',
      'call_customer': 'ಗ್ರಾಹಕರಿಗೆ ಕರೆ ಮಾಡಿ',
      'active_jobs': 'ಪ್ರಸ್ತುತ ಕೆಲಸಗಳು',
      'past_jobs': 'ಪೂರ್ಣಗೊಂಡ ಕೆಲಸಗಳ ಇತಿಹಾಸ',
      'no_active_jobs': 'ಪ್ರಸ್ತುತ ಯಾವುದೇ ಸಕ್ರಿಯ ಕೆಲಸಗಳಿಲ್ಲ.',
      'no_bookings': 'ಇನ್ನೂ ಯಾವುದೇ ಬುಕಿಂಗ್‌ಗಳಿಲ್ಲ.',
      'certification_title': 'ಕಾರ್ಮಿಕ ಪರಿಶೀಲನೆ ಮತ್ತು ಪ್ರಮಾಣೀಕರಣ',
      'certification_subtitle': 'ಸರ್ಕಾರಿ ಸಹಕಾರಿ ಪ್ರಮಾಣೀಕೃತ • ಗರಿಷ್ಠ ಗಳಿಕೆ',
      'aadhaar_verification': 'ಆಧಾರ್ ಪರಿಶೀಲನೆ',
      'aadhaar_desc': 'ನಿಮ್ಮ 12-ಅಂಕಿಯ ಆಧಾರ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.',
      'face_card_title': 'ಫೇಸ್ ಕಾರ್ಡ್ ಮತ್ತು ನ್ಯಾಯಸಮ್ಮತ ಪರಿಶೀಲನೆ',
      'face_card_desc': 'ವಂಚನೆ ತಡೆಗಟ್ಟಲು ನೇರ ಮುಖ ಗುರುತಿಸುವಿಕೆ.',
      'trade_cert_title': 'ವೃತ್ತಿ ಮತ್ತು ಕೌಶಲ್ಯ ಪ್ರಮಾಣಪತ್ರ',
      'trade_cert_desc': 'ITI ಅಥವಾ ಕೌಶಲ್ಯ ಪ್ರಮಾಣಪತ್ರಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
      'submit_verification': 'ಪರಿಶೀಲನೆಗಾಗಿ ಸಲ್ಲಿಸಿ',
      'verification_status_pending': 'ಪರಿಶೀಲನೆ ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ',
      'verification_status_verified': '100% ಪ್ರಮಾಣೀಕೃತ ಸದಸ್ಯ',
      'fairness_score_label': 'ಸಹಕಾರಿ ನ್ಯಾಯಸಮ್ಮತ ಅಂಕ',
      'nearby_demand': 'ಹತ್ತಿರದ ಗ್ರಾಹಕರ ಬೇಡಿಕೆ',
      'filter_radius': 'ತ್ರಿಜ್ಯ ಫಿಲ್ಟರ್',
    },
  };
}
